export const countryList = [
	"Afghanistan ",
	"Ethiopia",
	"Albanie ",
	"Algérie ",
	"Samoa américaines" ,
	 "Andorre",
	"Angola ",
	"Anguilla",
    "Antarctique ",
	"Antigua-et-Barbuda ",
	"Argentine ",
	 "Arménie ",
	 "Aruba ",
	 "Australie ",
	"Autriche ",
	"Azerbaïdjan ",
	"Bahamas (le) ",
/*	« Bahreïn »,
	« Bangladesh »,
	« Barbade »,
	« Biélorussie »,
	« Belgique »,
	« Belize »,
	« Bénin »,
	« Bermudes »,
	« Bhoutan »,
	« Bolivie (État plurinational de) »,
	« Bonaire, Saint-Eustache et Saba »,
	« Bosnie-Herzégovine »,
	« Botswana »,
	« Île Bouvet »,
	« Brésil »,
	« Territoire britannique de l’océan Indien (le) »,
	« Brunei Darussalam »,
	« Bulgarie »,
	« Burkina Faso »,
	« Burundi »,
	« Cabo Verde »,
	« Cambodge »,
	« Cameroun »,
	« Canada »,
	« Îles Caïmans (le) »,
	« République centrafricaine (la) »,
	« Tchad »,
	« Chili »,
	« Chine »,
	« Île Christmas »,
	« Îles Cocos (Keeling) (le) »,
	« Colombie »,
	« Comores (le) »,
	« Congo (République démocratique du) »,
	« Congo (le) »,
	« Îles Cook (le) »,
	« Costa Rica »,
	« Croatie »,
	« Cuba »,
	« Curaçao »,
	« Chypre »,
	« Tchéquie »,
	« Côte d’Ivoire »,
	« Danemark »,
	« Djibouti »,
	« Dominique »,
	« République dominicaine (le) »,
	« Équateur »,
	« Egypte »,
	« El Salvador »,
	« Guinée équatoriale »,
	« Érythrée »,
	« Estonie »,
	« Eswatini »,
	« Ethiopie »,
	« Îles Falkland (les) [Malvinas] »,
	« Îles Féroé (le) »,
	« Fidji »,
	« Finlande »,
	« France »,
	« Français Guyane »,
	« polynésie Français »,
	« Français Territoires du Sud (le) »,
	« Gabon »,
	« Gambie (le) »,
	« Géorgie »,
	« Allemagne »,
	« Ghana »,
	« Gibraltar »,
	« Grèce »,
	« Groenland »,
	« Grenade »,
	« Guadeloupe »,
	« Guam »,
	« Guatemala »,
	« Guernesey »,
	« Guinée »,
	« Guinée-Bissau »,
	« Guyana »,
	« Haïti »,
	« L’île Heard et les îles McDonald »,
	« Saint-Siège (le) »,
	« Honduras »,
	« Hong Kong »,
	« Hongrie »,
	« Islande »,
	« Inde »,
	« Indonésie »,
	« Iran (République islamique d') »,
	« Irak »,
	« Irlande »,
	« Île de Man »,
	« Israël »,
	« Italie »,
	« Jamaïque »,
	« Japon »,
	« Jersey »,
	« Jordanie »,
	« Kazakhstan »,
	« Kenya »,
	« Kiribati »,
	« Corée (République populaire démocratique de) »,
	« Corée (République de) »,
	« Koweït »,
	« Kirghizistan »,
	« République démocratique populaire lao (la) »,
	« Lettonie »,
	« Liban »,
	« Lesotho »,
	« Libéria »,
	« Libye »,
	« Liechtenstein »,
	« Lituanie »,
	« Luxembourg »,
	« Macao »,
	« Madagascar »,
	« Malawi »,
	« Malaisie »,
	« Maldives »,
	« Mali »,
	« Malte »,
	« Îles Marshall (le) »,
	« Martinique »,
	« Mauritanie »,
	« Maurice »,
	« Mayotte »,
	« Mexique »,
	« Micronésie (États fédérés de) »,
	« Moldova (République de) »,
	« Monaco »,
	« Mongolie »,
	« Monténégro »,
	« Montserrat »,
	« Maroc »,
	« Mozambique »,
	« Myanmar »,
	« Namibie »,
	« Nauru »,
	« Népal »,
	« Pays-Bas (le) »,
	« Nouvelle-Calédonie »,
	« Nouvelle-Zélande »,
	« Nicaragua »,
	« Niger (le) »,
	« Nigéria »,
	« Niue »,
	« Île Norfolk »,
	« Îles Mariannes du Nord (les) »,
	« Norvège »,
	« Oman »,
	« Pakistan »,
	« Palaos »,
	« Palestine, État de »,
	« Panama »,
	« Papouasie-Nouvelle-Guinée »,
	« Paraguay »,
	« Pérou »,
	« Philippines (le) »,
	« Pitcairn »,
	« Pologne »,
	« Portugal »,
	« Porto Rico »,
	« Qatar »,
	« République de Macédoine du Nord »,
	« Roumanie »,
	« Fédération de Russie (le) »,
	« Rwanda »,
	« Réunion »,
	« Saint Barthélemy »,
	« Sainte-Hélène, Ascension et Tristan da Cunha »,
	« Saint-Kitts-et-Nevis »,
	« Sainte-Lucie »,
	« Saint Martin (Français partie) »,
	« Saint Pierre-et-Miquelon »,
	« Saint-Vincent-et-les Grenadines »,
	« Samoa »,
	« Saint-Marin »,
	« Sao Tomé-et-Principe »,
	« Arabie saoudite »,
	« Sénégal »,
	« Serbie »,
	« Seychelles »,
	« Sierra Leone »,
	« Singapour »,
	« Sint Maarten (partie néerlandaise) »,
	« Slovaquie »,
	« Slovénie »,
	« Îles Salomon »,
	« Somalie »,
	« Afrique du Sud »,
	« Géorgie du Sud et îles Sandwich du Sud »,
	« Soudan du Sud »,
	« Espagne »,
	« Sri Lanka »,
	« Soudan (le) »,
	« Suriname »,
	« Svalbard et Jan Mayen »,
	« Suède »,
	« Suisse »,
	« République arabe syrienne »,
	« Taïwan »,
	« Tadjikistan »,
	« Tanzanie, République-Unie de »,
	« Thaïlande »,
	« Timor-Leste »,
	« Togo »,
	« Tokélaou »,
	« Tonga »,
	« Trinité-et-Tobago »,
	« Tunisie »,
	« Turquie »,
	« Turkménistan »,
	« Îles Turques et Caïques (les) »,
	« Tuvalu »,
	« Ouganda »,
	« Ukraine »,
	« Émirats arabes unis (le) »,
	« Royaume-Uni de Grande-Bretagne et d’Irlande du Nord (le) »,
	« Îles mineures éloignées des États-Unis (le) »,
	« États-Unis d’Amérique (le) »,
	« Uruguay »,
	« Ouzbékistan »,
	« Vanuatu »,
	« Venezuela (République bolivarienne de) »,
	« Viet Nam »,
	« Îles Vierges (britanniques) »,
	« Îles Vierges (États-Unis) » ,
	« Wallis et Futuna »,
	« Sahara occidental »,
	« Yémen »,
	« Zambie »,
	« Zimbabwe »,
	« Îles Åland »*/
];
